name: SuperHardcore
version: '1.2-SNAPSHOT'
main: forwynn.superHardcore.SuperHardcore
api-version: '1.21'
authors: [ Foreverably ]
website: https://superhardcore.forwynn.net
description: A Spigot/Paper Minecraft plugin that enhances the survival experience.
